# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MarketPlace' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MarketPlace
  pod 'Charts'

  target 'MarketPlaceTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MarketPlaceUITests' do
    # Pods for testing
  end

end
